table 'dotnet modernisation'
	lineageTag: 3a40666f-2f15-446a-8b97-f65a962711e0

	column Org
		dataType: string
		lineageTag: 3619627b-7301-4432-becb-350a1f8e0337
		summarizeBy: none
		sourceColumn: Org

		annotation SummarizationSetBy = Automatic

	column Repo
		dataType: string
		lineageTag: 296ba59b-aa39-4091-b968-d1f1cb3c2332
		summarizeBy: none
		sourceColumn: Repo

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		lineageTag: 713fa27b-1f5c-4642-9e78-4944431b3d39
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column PR
		dataType: string
		lineageTag: 81ecbd21-477c-444f-8d05-13a6786e3ced
		summarizeBy: none
		sourceColumn: PR

		annotation SummarizationSetBy = Automatic

	column Commit
		dataType: string
		lineageTag: b725868c-3856-46fa-92a6-4de6016da654
		summarizeBy: none
		sourceColumn: Commit

		annotation SummarizationSetBy = Automatic

	column Committer
		dataType: string
		lineageTag: 4c441bae-ef60-4afd-ae0b-7b52782bd67d
		summarizeBy: none
		sourceColumn: Committer

		annotation SummarizationSetBy = Automatic

	column 'Assessment Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 41088069-b468-484b-8c2b-b40eb509f8ab
		summarizeBy: none
		sourceColumn: Assessment Date

		variation Variation
			isDefault
			relationship: 0702c12c-1728-4389-b8b3-5998a1473075
			defaultHierarchy: LocalDateTable_3dbf6775-7619-41e9-9ef7-87efd2cc93c1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Assessment Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2e479461-c098-437f-ac32-eba2307e6fd4
		summarizeBy: none
		sourceColumn: Assessment Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Extension
		dataType: string
		lineageTag: b10711b7-6e8e-401a-b61f-c94e9c298509
		summarizeBy: none
		sourceColumn: Extension

		annotation SummarizationSetBy = Automatic

	column 'Folder Path'
		dataType: string
		lineageTag: 4a0b98a2-e5b2-45bf-9842-45c9d10642be
		summarizeBy: none
		sourceColumn: Folder Path

		annotation SummarizationSetBy = Automatic

	column analysisStartTime
		dataType: string
		lineageTag: ae323169-91de-4675-91f5-e4bf23f7d586
		summarizeBy: none
		sourceColumn: analysisStartTime

		annotation SummarizationSetBy = Automatic

	column analysisEndTime
		dataType: string
		lineageTag: 95636b09-df80-40c8-a17d-0528a209ce48
		summarizeBy: none
		sourceColumn: analysisEndTime

		annotation SummarizationSetBy = Automatic

	column projects
		dataType: string
		lineageTag: a65bc234-f5ab-43c5-b64f-a906dd1bcae7
		summarizeBy: none
		sourceColumn: projects

		annotation SummarizationSetBy = Automatic

	column settings_components_code
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 74fd6a36-f02c-4329-919d-1fc8b02d9c5d
		summarizeBy: none
		sourceColumn: settings_components_code

		annotation SummarizationSetBy = Automatic

	column settings_components_binaries
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 96ca6c3e-1803-400e-a0d5-349f394ea5b7
		summarizeBy: none
		sourceColumn: settings_components_binaries

		annotation SummarizationSetBy = Automatic

	column settings_targetId
		dataType: string
		lineageTag: 22c076da-9462-41a0-8ffc-57fef4b36845
		summarizeBy: none
		sourceColumn: settings_targetId

		annotation SummarizationSetBy = Automatic

	column settings_targetDisplayName
		dataType: string
		lineageTag: 6dcf0daa-eb8a-4ca9-9d33-9bdaea73db63
		summarizeBy: none
		sourceColumn: settings_targetDisplayName

		annotation SummarizationSetBy = Automatic

	column settings_visuals_elements
		dataType: string
		lineageTag: 1c29c223-b7e8-4003-8f6f-20f8737b2729
		summarizeBy: none
		sourceColumn: settings_visuals_elements

		annotation SummarizationSetBy = Automatic

	column settings_visuals_pages_projects
		dataType: string
		lineageTag: 6820d21a-7776-4d31-bd9e-2eb4d9caa392
		summarizeBy: none
		sourceColumn: settings_visuals_pages_projects

		annotation SummarizationSetBy = Automatic

	column stats_summary_projects
		dataType: int64
		formatString: 0
		lineageTag: cf0678e9-e2fa-4c0c-984a-58d0a7077898
		summarizeBy: sum
		sourceColumn: stats_summary_projects

		annotation SummarizationSetBy = Automatic

	column stats_summary_issues
		dataType: int64
		formatString: 0
		lineageTag: d25d60ca-aa5f-4f79-965e-9774f8598566
		summarizeBy: sum
		sourceColumn: stats_summary_issues

		annotation SummarizationSetBy = Automatic

	column stats_summary_incidents
		dataType: int64
		formatString: 0
		lineageTag: 0bd264aa-4366-4247-bbdb-76a99b5a657d
		summarizeBy: sum
		sourceColumn: stats_summary_incidents

		annotation SummarizationSetBy = Automatic

	column stats_summary_effort
		dataType: int64
		formatString: 0
		lineageTag: 9e55ae74-a889-4831-9fa7-8993ce3deea0
		summarizeBy: sum
		sourceColumn: stats_summary_effort

		annotation SummarizationSetBy = Automatic

	column stats_charts_severity_Mandatory
		dataType: int64
		formatString: 0
		lineageTag: 315e8149-38f7-4c73-be1d-c4ba40e4ff2a
		summarizeBy: sum
		sourceColumn: stats_charts_severity_Mandatory

		annotation SummarizationSetBy = Automatic

	column stats_charts_severity_Optional
		dataType: int64
		formatString: 0
		lineageTag: b71d9e6e-7530-45ba-b33a-71166a26f6c9
		summarizeBy: sum
		sourceColumn: stats_charts_severity_Optional

		annotation SummarizationSetBy = Automatic

	column stats_charts_severity_Potential
		dataType: int64
		formatString: 0
		lineageTag: 37140593-deab-4fb1-8c00-bae4e5c9045a
		summarizeBy: sum
		sourceColumn: stats_charts_severity_Potential

		annotation SummarizationSetBy = Automatic

	column stats_charts_severity_Information
		dataType: int64
		formatString: 0
		lineageTag: ac27d6a5-3527-4f82-bb7f-3cea3993f9fb
		summarizeBy: sum
		sourceColumn: stats_charts_severity_Information

		annotation SummarizationSetBy = Automatic

	column stats_charts_category_Scale
		dataType: int64
		formatString: 0
		lineageTag: 41d1e76c-a1e4-46c2-a457-099820f5adf1
		summarizeBy: sum
		sourceColumn: stats_charts_category_Scale

		annotation SummarizationSetBy = Automatic

	column 'rules_Scale.0001_id'
		dataType: string
		lineageTag: 95945915-0e12-4114-b02d-f00da7de99d2
		summarizeBy: none
		sourceColumn: rules_Scale.0001_id

		annotation SummarizationSetBy = Automatic

	column 'rules_Scale.0001_description'
		dataType: string
		lineageTag: 76be4d57-dc46-4701-9ad8-aad3dac10490
		summarizeBy: none
		sourceColumn: rules_Scale.0001_description

		annotation SummarizationSetBy = Automatic

	column 'rules_Scale.0001_label'
		dataType: string
		lineageTag: 10e83105-c674-463a-a211-dccf2892030c
		summarizeBy: none
		sourceColumn: rules_Scale.0001_label

		annotation SummarizationSetBy = Automatic

	column 'rules_Scale.0001_severity'
		dataType: string
		lineageTag: 9ec2d757-671b-4705-907e-9c541a8309a3
		summarizeBy: none
		sourceColumn: rules_Scale.0001_severity

		annotation SummarizationSetBy = Automatic

	column 'rules_Scale.0001_effort'
		dataType: string
		lineageTag: 5ba766c3-6513-4ee8-b4e8-dda2b2c42e6c
		summarizeBy: none
		sourceColumn: rules_Scale.0001_effort

		annotation SummarizationSetBy = Automatic

	column 'rules_Scale.0001_links'
		dataType: string
		lineageTag: 537d3b1c-e20b-4d7c-b4db-e6482520d8bc
		summarizeBy: none
		sourceColumn: rules_Scale.0001_links

		annotation SummarizationSetBy = Automatic

	partition 'dotnet modernisation' = m
		mode: import
		source =
				let
				  Source = AzureStorage.Blobs("https://appcatstorage.blob.core.windows.net/"),
				  #"Navigation 1" = Source{[Name = "appcat"]}[Data],
				  #"Filtered rows" = Table.SelectRows(#"Navigation 1", each ([Extension] = ".json")),
				  #"Filtered hidden files" = Table.SelectRows(#"Filtered rows", each [Attributes]?[Hidden]? <> true),
				  #"Split column by delimiter" = Table.SplitColumn(#"Filtered hidden files", "Name", Splitter.SplitTextByDelimiter("/"), {"Name.1", "Name.2", "Name.3", "Name.4", "Name.5", "Name.6", "Name.7"}),
				  #"Renamed columns" = Table.RenameColumns(#"Split column by delimiter", {{"Name.1", "Org"}, {"Name.2", "Repo"}, {"Name.3", "Branch"}, {"Name.4", "PR"}, {"Name.5", "Commit"}, {"Name.6", "Committer"}, {"Name.7", "Date"}}),
				  #"Replaced value" = Table.ReplaceValue(#"Renamed columns", "org=", "", Replacer.ReplaceText, {"Org"}),
				  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", "repo=", "", Replacer.ReplaceText, {"Repo"}),
				  #"Replaced value 2" = Table.ReplaceValue(#"Replaced value 1", "branch=", "", Replacer.ReplaceText, {"Branch"}),
				  #"Replaced value 3" = Table.ReplaceValue(#"Replaced value 2", "pr=", "", Replacer.ReplaceText, {"PR"}),
				  #"Replaced value 4" = Table.ReplaceValue(#"Replaced value 3", "commit=", "", Replacer.ReplaceText, {"Commit"}),
				  #"Replaced value 5" = Table.ReplaceValue(#"Replaced value 4", "committer=", "", Replacer.ReplaceText, {"Committer"}),
				  #"Replaced value 6" = Table.ReplaceValue(#"Replaced value 5", "Z.json", "", Replacer.ReplaceText, {"Date"}),
				  #"Split column by delimiter 1" = Table.SplitColumn(#"Replaced value 6", "Date", Splitter.SplitTextByDelimiter("T"), {"Date.1", "Date.2"}),
				  #"Changed column type" = Table.TransformColumnTypes(#"Split column by delimiter 1", {{"Date.1", type date}, {"Date.2", type text}}, "en-US"),
				  #"Renamed columns 1" = Table.RenameColumns(#"Changed column type", {{"Date.1", "Assessment Date"}}),
				  #"Replaced value 7" = Table.ReplaceValue(#"Renamed columns 1", "-", ":", Replacer.ReplaceText, {"Date.2"}),
				  #"Changed column type 1" = Table.TransformColumnTypes(#"Replaced value 7", {{"Date.2", type time}}),
				  #"Renamed columns 2" = Table.RenameColumns(#"Changed column type 1", {{"Date.2", "Assessment Time"}}),
				  #"Removed columns" = Table.RemoveColumns(#"Renamed columns 2", {"Attributes", "Date created", "Date modified", "Date accessed"}),
				  #"Filtered hidden files 1" = Table.SelectRows(#"Removed columns", each [Attributes]?[Hidden]? <> true),
				  #"Invoke custom function" = Table.AddColumn(#"Filtered hidden files 1", "Transform file", each #"Transform file"([Content])),
				 // #"Removed other columns" = Table.SelectColumns(#"Invoke custom function", {"Content"}),
				  #"Expanded table column" = Table.ExpandTableColumn(#"Invoke custom function" , "Transform file", Table.ColumnNames(#"Transform file"(#"Sample file"))),
				  #"Removed columns 1" = Table.RemoveColumns(#"Expanded table column", {"Content"}),
				  #"Changed column type 2" = Table.TransformColumnTypes(#"Removed columns 1", {{"settings_components_code", type logical}, {"settings_components_binaries", type logical}, {"stats_summary_projects", Int64.Type}, {"stats_summary_issues", Int64.Type}, {"stats_summary_incidents", Int64.Type}, {"stats_summary_effort", Int64.Type}, {"stats_charts_severity_Mandatory", Int64.Type}, {"stats_charts_severity_Optional", Int64.Type}, {"stats_charts_severity_Potential", Int64.Type}, {"stats_charts_severity_Information", Int64.Type}, {"stats_charts_category_Scale", Int64.Type}})
				in
				  #"Changed column type 2"

	annotation PBI_ResultType = Table

